version: '3.8'
volumes:
  test_data:

services:
  db:
    container_name: db
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pa55word
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - test_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    container_name: test-backend
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pa55word
      - POSTGRES_DB=postgres
    links:
      - db
#
#  frontend:
#    build: ./frontend
#    container_name: test-frontend
#    ports:
#      - "4200:4200"
#    links:
#      - backend