version: '3.8'
volumes:
  test_data:

services:
  db:
    container_name: db
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pa55word
    ports:
      - "5432:5432"
    volumes:
      - test_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pa55word
    links:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/node_modules:/usr/src/app/node_modules
    ports:
      - "4200:80"
    links:
      - backend
